apiVersion: apps/v1
kind: Deployment
metadata:
  name: kevin-dotnet
spec:
  selector:
    matchLabels:
      app: kevin-dotnet
  replicas: 1
  template:
    metadata:
      labels:
        app: kevin-dotnet
    spec:
      containers:
        - name: kevin-dotnet
          image: quay-registry.apps.vgqa2hi9.eastus.aroapp.io/coelsa/first-app/kevin-dotnet
          ports:
            - containerPort: 8080

